"""fase 1: join_code, active_org, cost_centers

Revision ID: 55df6f3252eb
Revises: e2a2db2c8957
Create Date: 2026-06-24 14:16:10.689845
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55df6f3252eb'
down_revision: Union[str, None] = 'e2a2db2c8957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_org_cost_center_name')
    )
    op.add_column('organizations', sa.Column('join_code', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'organizations', ['join_code'])
    op.add_column('users', sa.Column('active_org_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active_org_id')
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_column('organizations', 'join_code')
    op.drop_table('cost_centers')
    # ### end Alembic commands ###
